version: 1.0.6.2

environment:
  nugetVersion: 1.0.6.2

init:
  - ps: Update-AppveyorBuild -Version $env:nugetVersion

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(nugetVersion)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- nuget restore src\allure-nunit.sln

build:
  verbosity: minimal

test: off

artifacts:
- path: '**\NUnit.Allure*.nupkg'

for:
-
  branches:
      only:
        - develop
  version: 1.0.7-beta{build}
  environment:
    nugetVersion: 1.0.7-beta$(APPVEYOR_BUILD_NUMBER)